services:
  registry_frontend:
    container_name: registry_fronted
    image: konradkleine/docker-registry-frontend:v2
    environment:
      ENV_DOCKER_REGISTRY_HOST: '172.18.60.19'
      ENV_DOCKER_REGISTRY_PORT: '5000'
    ports:
      - 8080:80
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./dockerData/registry:/data
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
