services:
  lb:
    image: traefik:v2.5
    container_name: balancer
    restart: unless-stopped
    command:
      - "--api.insecure=true"  # Habilita la API para debugging (quítalo en producción)
      - "--providers.docker=true"
      - "--entrypoints.web.address=127.0.0.1:80"  # Define el entrypoint en 127.0.0.1
    ports:
      - "80:80"
      - "443:443"
      - "1936:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    networks:
      - utp_network
    labels:
      - "traefik.enable=true"
networks:
  utp_network:
    external: true
